name: 'Font-TTF-Scripts'
author: [ 'Martin Hosken <martin_hosken@sil.org>' ]
version: '1.04'
description:  "various scripts using the Font::TTF module"
license: 'artistic2'
homepage: "http://scripts.sil.org/FontUtils"
